[package]
name = "kahoot-cli"
version = "0.0.3"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"

[dependencies]
kahoot = { path = "../kahoot" }
rand = "0.7.3"
tokio = "0.2.13"
lazy_static = "1.4.0"
