[package]
name = "kahoot-cli"
version = "0.0.3"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kahoot = { path = "../" }